#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:
    apisix-dashboard:
        image: apache/apisix-dashboard:3.0.1-alpine
        container_name: apisix-dashboard
        restart: always
        volumes:
            - ./config/apisix_dashboard/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
        ports:
            - "9000:9000"
        networks:
            - apisix

    apisix:
        image: "apache/apisix:3.4.1-debian"
        container_name: apisix
        restart: always
        volumes:
            - ./config/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
            - ./build/go-runner:/usr/local/apisix/go-runner
        environment:
            - APISIX_LISTEN_ADDRESS=unix:/tmp/go-runner.sock /usr/local/apisix/go-runner run
            - APISIX_CONF_EXPIRE_TIME=3600
        depends_on:
            - etcd
        ports:
            - "9180:9180/tcp"
            - "9080:9080/tcp"
            - "9091:9091/tcp"
            - "9443:9443/tcp"
        networks:
            - apisix

    etcd:
        image: bitnami/etcd:3.4.9
        user: root
        restart: always
        container_name: etcd
        volumes:
            - ./config/etcd_data:/etcd_data
        environment:
            - ETCD_DATA_DIR=/etcd_data
            - ETCD_ENABLE_V2=true
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        ports:
            - "2379:2379/tcp"
        networks:
            - apisix

    testresty:
        image: kennethreitz/httpbin
        restart: unless-stopped
        container_name: testresty
        ports:
            - "1980:80"
        networks:
            - apisix

networks:
  apisix:
    driver: bridge